// skills/modern-webapp-design/assets/templates/vue-tailwind-app-shell.vue
<script setup>
import { defineAsyncComponent } from "vue";

const DashboardPage = defineAsyncComponent(() => import("./pages/DashboardPage.vue"));
</script>

<template>
  <div class="min-h-screen bg-slate-50 text-slate-900">
    <header class="sticky top-0 z-20 border-b border-slate-200 bg-white/90 backdrop-blur">
      <div class="mx-auto flex max-w-6xl items-center justify-between px-4 py-3">
        <h1 class="text-lg font-semibold tracking-tight">Product Console</h1>
        <button class="rounded-md bg-teal-600 px-4 py-2 text-sm font-medium text-white hover:bg-teal-700">
          New Report
        </button>
      </div>
    </header>

    <main class="mx-auto max-w-6xl px-4 py-8">
      <Suspense>
        <DashboardPage />
        <template #fallback>
          <div class="text-slate-500">Loading dashboard...</div>
        </template>
      </Suspense>
    </main>
  </div>
</template>

// skills/modern-webapp-design/assets/templates/react-tailwind-app-shell.jsx
import { Suspense, lazy } from "react";

const Dashboard = lazy(() => import("./pages/Dashboard"));

export default function App() {
  return (
    <div className="min-h-screen bg-slate-50 text-slate-900">
      <header className="sticky top-0 z-20 border-b border-slate-200 bg-white/90 backdrop-blur">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3">
          <h1 className="text-lg font-semibold tracking-tight">Product Console</h1>
          <button className="rounded-md bg-teal-600 px-4 py-2 text-sm font-medium text-white hover:bg-teal-700">
            New Report
          </button>
        </div>
      </header>

      <main className="mx-auto max-w-6xl px-4 py-8">
        <Suspense fallback={<div className="text-slate-500">Loading dashboard...</div>}>
          <Dashboard />
        </Suspense>
      </main>
    </div>
  );
}
